# Generated by Django 4.1.2 on 2022-11-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=300, null=True)),
                ('pro_image', models.ImageField(upload_to='upload/product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.category')),
            ],
        ),
    ]
