# Generated by Django 4.1.2 on 2022-11-25 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=300, null=True)),
                ('mobile_no', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 25, 22, 36, 20, 919541))),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.signup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.product')),
            ],
        ),
    ]
